### PR TITLE
WiP: Add schema.org support

### LINKED ISSUE #73: Improved / generic schema.org support
We have all the machinery we need for a better schema.org support, and to allow generating metadata in **json+ld** format

We should definitely make easier and more straightforward to output rich and valid schema.org metadata

### PR DESCRIPTION
**Pull request by yakky**
Add schema.org by adding a separate set of data to handle it

As the schema.org standard keeps adding more type and properties, trying to map them would be pretty pointless: it would be too complicated to maintain.

Thus a leaner approach has been designed here: the developer has to create dictionaries of properties, with some syntactic sugar which automatically replaces ``Meta`` and ``ModelMeta`` instances with their schema to allow to easily build nested structures programmatically

* [x] implementation
* [x] documentation (but still needs validation)
* [ ] tests

Fix #73

### CODE REVIEW

**Comment by batisteo** [comment]
@yakky This feature would be useful. How could I help with this PR? Anything more than fixing/writing tests?

**Comment by yakky** [comment]
I think that at this stage, the validation of the the API and the overall design is the most needed help
Code contribution is obviously welcome, but having more eyeballs reviewing the code is obviously welcome
The single most critical part is the serializer (or rather, the pre-serializer) https://github.com/nephila/django-meta/pull/76/files#diff-6cc6678cc74aae622c25042ad7e88fe0R197

**Comment by khrizo** [comment]
Would be great to have this implemented

**Comment by svandeneertwegh** [comment]
@yakky Can this feature be merged?

**Comment by protoroto** [comment]
@yakky I'll close this as it is superseded by #166 . @svandeneertwegh @khrizo this feature is now released on 2.4.0 version.

**Pull request closed without merging**
