### PR TITLE
Replace usage of ugettext lazy

### LINKED ISSUE #130: Django 4.0 ugettext_lazy error
## Description

As per Django 4.0

> django.utils.translation.ugettext(), ugettext_lazy(), ugettext_noop(), ungettext(), and ungettext_lazy() are removed.

## Steps to reproduce

Just install and runserver, it will fail with error

## Versions

Python: 3.10
Django: 4.0
Meta: latest

## Expected behaviour

No error

## Actual behaviour

Error

## Additional information

Any replacement for this library folks?

### PR DESCRIPTION
**Pull request by peterth3**
# Description

Describe:

Replaces django.utils.translation.ugettext_lazy with django.utils.translation.gettext_lazy

## References

Fixes #130 

# Checklist

* [x] I have read the [contribution guide](https://django-meta.readthedocs.io/en/latest/contributing.html)
* [x] Code lint checked via `inv lint`
* [x] ``changes`` file included (see [docs](https://django-meta.readthedocs.io/en/latest/contributing.html#pull-request-guidelines))
* [x] Usage documentation added in case of new features (no new features)
* [x] Tests added (not needed because changes are to imports)

### CODE REVIEW

**Comment by karbassi** [comment]
LGTM. 👍🏽 

Would be awesome if you could merge this.

**Comment by peterth3** [comment]
@yakky Do you need me to add anything else in this PR to merge? The changes are very simple.

**Comment by rhimmelbauer** [comment]
@peterth3 thanks for putting in the fix!. @yakky do you have an ETA for merging and releasing a new version?

**Comment by urlsangel** [comment]
Hi @yakky 

+1 on @rhimmelbauer's question: https://github.com/nephila/django-meta/pull/132#issuecomment-1083417296

This is blocking an update for a Django 4 project I'm working on, it would be awesome if this could be released to PYPI?

Thanks,

Russell.

**Comment by ZainJaffer** [comment]
+1 here, I have a project that's currently blocked - any updates on this?

**Comment by afdy** [comment]
+1 please merge. 

Is this project still maintained or am I missing something? :)

**Comment by peterth3** [comment]
@yakky I am assuming that this PR is stuck because of the incomplete tasks on my PR, so I added a change file and tried following your process the best I could. Please let me know if there are any other changes you need to merge this or if there's anything I can do to help. 

The last release for `django-meta` was almost 2 years ago, so it would be awesome to see a new release with this change sometime soon.

**Review by yakky — APPROVED** [review]

**Comment by yakky** [comment]
@peterth3 thanks a lot for your contribution. Expect a release in the next couple of days

**Pull request merged**
