### PR TITLE
More twitter properties

### PR DESCRIPTION
**Pull request by m-vdb**
Hi guys,

I added some missing properties on the twitter namespace: `creator` and `card`. (documentation here https://dev.twitter.com/cards/getting-started). Added documentation and tests.

Let me know if this works for you,

Max.

### CODE REVIEW

**Comment by m-vdb** [comment]
cc @yakki

**Comment by yakky** [comment]
Awesome, thanks!

**Comment by m-vdb** [comment]
thanks for the quick merge!

**Comment by m-vdb** [comment]
Oh and I just saw you did a `pip` release, thanks :heavy_multiplication_x: :two:

**Pull request merged**
