### PR TITLE
fix twitter props

### PR DESCRIPTION
**Pull request by m-vdb**
Hi @yakky 

This fixes some OG properties for twitter. Also, it might be nice to have tests on the template itself :)

Twitter reference: https://dev.twitter.com/cards/markup

### CODE REVIEW

**Comment by yakky** [comment]
@m-vdb thanks for fixing this!
Aren't templates covered by test already (https://github.com/nephila/django-meta/pull/45/commits/2418538d021c5bc59f74d7da8148123d5fa39c33)?

**Comment by m-vdb** [comment]
Ah yes I wrote the comment before finding the tests :)

**Comment by yakky** [comment]
1.3.2 released! Thanks for contributing!

**Comment by yakky** [comment]
:+1:
Updated release is on the launchpad

**Comment by m-vdb** [comment]
that was quick, thanks a lot!

**Pull request merged**
